namespace KyaniteBinder
{
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.guna2Panel3 = new global::Guna.UI2.WinForms.Guna2Panel();
			this.guna2ControlBox1 = new global::Guna.UI2.WinForms.Guna2ControlBox();
			this.guna2ControlBox2 = new global::Guna.UI2.WinForms.Guna2ControlBox();
			this.label1 = new global::System.Windows.Forms.Label();
			this.label3 = new global::System.Windows.Forms.Label();
			this.openFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.builderPanel = new global::Guna.UI2.WinForms.Guna2Panel();
			this.guna2Button5 = new global::Guna.UI2.WinForms.Guna2Button();
			this.fileList = new global::System.Windows.Forms.ListBox();
			this.guna2Button4 = new global::Guna.UI2.WinForms.Guna2Button();
			this.guna2Button3 = new global::Guna.UI2.WinForms.Guna2Button();
			this.guna2Button2 = new global::Guna.UI2.WinForms.Guna2Button();
			this.guna2Button1 = new global::Guna.UI2.WinForms.Guna2Button();
			this.compilerPanel = new global::Guna.UI2.WinForms.Guna2Panel();
			this.guna2Button7 = new global::Guna.UI2.WinForms.Guna2Button();
			this.guna2Button6 = new global::Guna.UI2.WinForms.Guna2Button();
			this.resultsTxt = new global::System.Windows.Forms.TextBox();
			this.filenameTxt = new global::Guna.UI2.WinForms.Guna2TextBox();
			this.label2 = new global::System.Windows.Forms.Label();
			this.openFileDialog2 = new global::System.Windows.Forms.OpenFileDialog();
			this.guna2Panel3.SuspendLayout();
			this.builderPanel.SuspendLayout();
			this.compilerPanel.SuspendLayout();
			base.SuspendLayout();
			this.guna2Panel3.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.guna2Panel3.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2Panel3.Controls.Add(this.guna2ControlBox1);
			this.guna2Panel3.Controls.Add(this.guna2ControlBox2);
			this.guna2Panel3.Controls.Add(this.label1);
			this.guna2Panel3.Controls.Add(this.label3);
			this.guna2Panel3.Location = new global::System.Drawing.Point(-1, -1);
			this.guna2Panel3.Name = "guna2Panel3";
			this.guna2Panel3.ShadowDecoration.Parent = this.guna2Panel3;
			this.guna2Panel3.Size = new global::System.Drawing.Size(646, 49);
			this.guna2Panel3.TabIndex = 16;
			this.guna2Panel3.Paint += new global::System.Windows.Forms.PaintEventHandler(this.guna2Panel3_Paint);
			this.guna2Panel3.MouseDown += new global::System.Windows.Forms.MouseEventHandler(this.guna2Panel3_MouseDown);
			this.guna2ControlBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.guna2ControlBox1.ControlBoxType = 0;
			this.guna2ControlBox1.FillColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox1.HoverState.BorderColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox1.HoverState.FillColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox1.HoverState.IconColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2ControlBox1.HoverState.Parent = this.guna2ControlBox1;
			this.guna2ControlBox1.IconColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2ControlBox1.Location = new global::System.Drawing.Point(567, -1);
			this.guna2ControlBox1.Name = "guna2ControlBox1";
			this.guna2ControlBox1.PressedColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox1.ShadowDecoration.Parent = this.guna2ControlBox1;
			this.guna2ControlBox1.Size = new global::System.Drawing.Size(35, 49);
			this.guna2ControlBox1.TabIndex = 11;
			this.guna2ControlBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.guna2ControlBox2.FillColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox2.HoverState.BorderColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox2.HoverState.FillColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox2.HoverState.IconColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2ControlBox2.HoverState.Parent = this.guna2ControlBox2;
			this.guna2ControlBox2.IconColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2ControlBox2.Location = new global::System.Drawing.Point(597, -1);
			this.guna2ControlBox2.Name = "guna2ControlBox2";
			this.guna2ControlBox2.PressedColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.guna2ControlBox2.ShadowDecoration.Parent = this.guna2ControlBox2;
			this.guna2ControlBox2.Size = new global::System.Drawing.Size(35, 49);
			this.guna2ControlBox2.TabIndex = 10;
			this.label1.AutoSize = true;
			this.label1.Font = new global::System.Drawing.Font("Segoe UI", 12.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label1.ForeColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.label1.Location = new global::System.Drawing.Point(79, 10);
			this.label1.Name = "label1";
			this.label1.Size = new global::System.Drawing.Size(63, 23);
			this.label1.TabIndex = 1;
			this.label1.Text = "Binder";
			this.label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label3.AutoSize = true;
			this.label3.Font = new global::System.Drawing.Font("Segoe UI", 13f, global::System.Drawing.FontStyle.Bold);
			this.label3.ForeColor = global::System.Drawing.Color.White;
			this.label3.Location = new global::System.Drawing.Point(10, 11);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(76, 25);
			this.label3.TabIndex = 0;
			this.label3.Text = "Kyanite";
			this.label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.openFileDialog1.FileName = "openFileDialog1";
			this.openFileDialog1.FileOk += new global::System.ComponentModel.CancelEventHandler(this.openFileDialog1_FileOk);
			this.builderPanel.Controls.Add(this.guna2Button5);
			this.builderPanel.Controls.Add(this.fileList);
			this.builderPanel.Controls.Add(this.guna2Button4);
			this.builderPanel.Controls.Add(this.guna2Button3);
			this.builderPanel.Controls.Add(this.guna2Button2);
			this.builderPanel.Controls.Add(this.guna2Button1);
			this.builderPanel.Location = new global::System.Drawing.Point(0, 50);
			this.builderPanel.Name = "builderPanel";
			this.builderPanel.ShadowDecoration.Parent = this.builderPanel;
			this.builderPanel.Size = new global::System.Drawing.Size(642, 323);
			this.builderPanel.TabIndex = 0;
			this.guna2Button5.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button5.BorderRadius = 2;
			this.guna2Button5.BorderThickness = 1;
			this.guna2Button5.CheckedState.Parent = this.guna2Button5;
			this.guna2Button5.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button5.CustomImages.Parent = this.guna2Button5;
			this.guna2Button5.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button5.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button5.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button5.HoverState.Parent = this.guna2Button5;
			this.guna2Button5.Location = new global::System.Drawing.Point(24, 17);
			this.guna2Button5.Name = "guna2Button5";
			this.guna2Button5.ShadowDecoration.Parent = this.guna2Button5;
			this.guna2Button5.Size = new global::System.Drawing.Size(594, 41);
			this.guna2Button5.TabIndex = 28;
			this.guna2Button5.Text = "Compile";
			this.guna2Button5.Click += new global::System.EventHandler(this.guna2Button5_Click);
			this.fileList.BackColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.fileList.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.fileList.Font = new global::System.Drawing.Font("Consolas", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.fileList.ForeColor = global::System.Drawing.Color.FromArgb(222, 222, 222);
			this.fileList.FormattingEnabled = true;
			this.fileList.ItemHeight = 18;
			this.fileList.Location = new global::System.Drawing.Point(-1, 141);
			this.fileList.Name = "fileList";
			this.fileList.Size = new global::System.Drawing.Size(647, 182);
			this.fileList.TabIndex = 27;
			this.guna2Button4.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button4.BorderRadius = 2;
			this.guna2Button4.BorderThickness = 1;
			this.guna2Button4.CheckedState.Parent = this.guna2Button4;
			this.guna2Button4.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button4.CustomImages.Parent = this.guna2Button4;
			this.guna2Button4.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button4.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button4.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button4.HoverState.Parent = this.guna2Button4;
			this.guna2Button4.Location = new global::System.Drawing.Point(481, 94);
			this.guna2Button4.Name = "guna2Button4";
			this.guna2Button4.ShadowDecoration.Parent = this.guna2Button4;
			this.guna2Button4.Size = new global::System.Drawing.Size(137, 41);
			this.guna2Button4.TabIndex = 26;
			this.guna2Button4.Text = "Add ICON";
			this.guna2Button4.Click += new global::System.EventHandler(this.guna2Button4_Click);
			this.guna2Button3.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button3.BorderRadius = 2;
			this.guna2Button3.BorderThickness = 1;
			this.guna2Button3.CheckedState.Parent = this.guna2Button3;
			this.guna2Button3.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button3.CustomImages.Parent = this.guna2Button3;
			this.guna2Button3.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button3.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button3.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button3.HoverState.Parent = this.guna2Button3;
			this.guna2Button3.Location = new global::System.Drawing.Point(331, 94);
			this.guna2Button3.Name = "guna2Button3";
			this.guna2Button3.ShadowDecoration.Parent = this.guna2Button3;
			this.guna2Button3.Size = new global::System.Drawing.Size(137, 41);
			this.guna2Button3.TabIndex = 25;
			this.guna2Button3.Text = "Clear Files";
			this.guna2Button3.Click += new global::System.EventHandler(this.guna2Button3_Click);
			this.guna2Button2.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button2.BorderRadius = 2;
			this.guna2Button2.BorderThickness = 1;
			this.guna2Button2.CheckedState.Parent = this.guna2Button2;
			this.guna2Button2.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button2.CustomImages.Parent = this.guna2Button2;
			this.guna2Button2.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button2.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button2.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button2.HoverState.Parent = this.guna2Button2;
			this.guna2Button2.Location = new global::System.Drawing.Point(178, 94);
			this.guna2Button2.Name = "guna2Button2";
			this.guna2Button2.ShadowDecoration.Parent = this.guna2Button2;
			this.guna2Button2.Size = new global::System.Drawing.Size(137, 41);
			this.guna2Button2.TabIndex = 24;
			this.guna2Button2.Text = "Remove File";
			this.guna2Button2.Click += new global::System.EventHandler(this.guna2Button2_Click);
			this.guna2Button1.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button1.BorderRadius = 2;
			this.guna2Button1.BorderThickness = 1;
			this.guna2Button1.CheckedState.Parent = this.guna2Button1;
			this.guna2Button1.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button1.CustomImages.Parent = this.guna2Button1;
			this.guna2Button1.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button1.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button1.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button1.HoverState.Parent = this.guna2Button1;
			this.guna2Button1.Location = new global::System.Drawing.Point(24, 94);
			this.guna2Button1.Name = "guna2Button1";
			this.guna2Button1.ShadowDecoration.Parent = this.guna2Button1;
			this.guna2Button1.Size = new global::System.Drawing.Size(137, 41);
			this.guna2Button1.TabIndex = 23;
			this.guna2Button1.Text = "Add File";
			this.guna2Button1.Click += new global::System.EventHandler(this.guna2Button1_Click_1);
			this.compilerPanel.Controls.Add(this.guna2Button7);
			this.compilerPanel.Controls.Add(this.guna2Button6);
			this.compilerPanel.Controls.Add(this.resultsTxt);
			this.compilerPanel.Controls.Add(this.filenameTxt);
			this.compilerPanel.Controls.Add(this.label2);
			this.compilerPanel.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.compilerPanel.Location = new global::System.Drawing.Point(0, 47);
			this.compilerPanel.Name = "compilerPanel";
			this.compilerPanel.ShadowDecoration.Parent = this.compilerPanel;
			this.compilerPanel.Size = new global::System.Drawing.Size(642, 326);
			this.compilerPanel.TabIndex = 17;
			this.compilerPanel.Paint += new global::System.Windows.Forms.PaintEventHandler(this.compilerPanel_Paint);
			this.guna2Button7.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button7.BorderRadius = 2;
			this.guna2Button7.BorderThickness = 1;
			this.guna2Button7.CheckedState.Parent = this.guna2Button7;
			this.guna2Button7.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button7.CustomImages.Parent = this.guna2Button7;
			this.guna2Button7.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button7.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button7.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button7.HoverState.Parent = this.guna2Button7;
			this.guna2Button7.Location = new global::System.Drawing.Point(14, 112);
			this.guna2Button7.Name = "guna2Button7";
			this.guna2Button7.ShadowDecoration.Parent = this.guna2Button7;
			this.guna2Button7.Size = new global::System.Drawing.Size(82, 41);
			this.guna2Button7.TabIndex = 28;
			this.guna2Button7.Text = "Go Back";
			this.guna2Button7.Click += new global::System.EventHandler(this.guna2Button7_Click);
			this.guna2Button6.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button6.BorderRadius = 2;
			this.guna2Button6.BorderThickness = 1;
			this.guna2Button6.CheckedState.Parent = this.guna2Button6;
			this.guna2Button6.CustomBorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.guna2Button6.CustomImages.Parent = this.guna2Button6;
			this.guna2Button6.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.guna2Button6.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.guna2Button6.ForeColor = global::System.Drawing.Color.White;
			this.guna2Button6.HoverState.Parent = this.guna2Button6;
			this.guna2Button6.Location = new global::System.Drawing.Point(211, 112);
			this.guna2Button6.Name = "guna2Button6";
			this.guna2Button6.ShadowDecoration.Parent = this.guna2Button6;
			this.guna2Button6.Size = new global::System.Drawing.Size(216, 41);
			this.guna2Button6.TabIndex = 27;
			this.guna2Button6.Text = "Compile";
			this.guna2Button6.Click += new global::System.EventHandler(this.guna2Button6_Click);
			this.resultsTxt.BackColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.resultsTxt.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.resultsTxt.Font = new global::System.Drawing.Font("Consolas", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.resultsTxt.ForeColor = global::System.Drawing.Color.FromArgb(222, 222, 222);
			this.resultsTxt.Location = new global::System.Drawing.Point(0, 176);
			this.resultsTxt.Multiline = true;
			this.resultsTxt.Name = "resultsTxt";
			this.resultsTxt.Size = new global::System.Drawing.Size(642, 149);
			this.resultsTxt.TabIndex = 14;
			this.filenameTxt.BorderColor = global::System.Drawing.Color.FromArgb(110, 68, 255);
			this.filenameTxt.BorderRadius = 1;
			this.filenameTxt.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.filenameTxt.DefaultText = "";
			this.filenameTxt.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.filenameTxt.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.filenameTxt.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.filenameTxt.DisabledState.Parent = this.filenameTxt;
			this.filenameTxt.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.filenameTxt.FillColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			this.filenameTxt.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.filenameTxt.FocusedState.Parent = this.filenameTxt;
			this.filenameTxt.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.filenameTxt.HoverState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.filenameTxt.HoverState.Parent = this.filenameTxt;
			this.filenameTxt.Location = new global::System.Drawing.Point(211, 64);
			this.filenameTxt.Name = "filenameTxt";
			this.filenameTxt.PasswordChar = '\0';
			this.filenameTxt.PlaceholderText = "";
			this.filenameTxt.SelectedText = "";
			this.filenameTxt.ShadowDecoration.Parent = this.filenameTxt;
			this.filenameTxt.Size = new global::System.Drawing.Size(216, 25);
			this.filenameTxt.TabIndex = 13;
			this.label2.AutoSize = true;
			this.label2.Font = new global::System.Drawing.Font("Consolas", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label2.ForeColor = global::System.Drawing.Color.White;
			this.label2.Location = new global::System.Drawing.Point(271, 27);
			this.label2.Name = "label2";
			this.label2.Size = new global::System.Drawing.Size(80, 18);
			this.label2.TabIndex = 12;
			this.label2.Text = "File Name";
			this.label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.openFileDialog2.FileName = "openFileDialog2";
			this.openFileDialog2.FileOk += new global::System.ComponentModel.CancelEventHandler(this.openFileDialog2_FileOk);
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.FromArgb(24, 24, 24);
			base.ClientSize = new global::System.Drawing.Size(643, 371);
			base.Controls.Add(this.guna2Panel3);
			base.Controls.Add(this.builderPanel);
			base.Controls.Add(this.compilerPanel);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "Form1";
			this.Text = "Form1";
			base.Load += new global::System.EventHandler(this.Form1_Load);
			this.guna2Panel3.ResumeLayout(false);
			this.guna2Panel3.PerformLayout();
			this.builderPanel.ResumeLayout(false);
			this.compilerPanel.ResumeLayout(false);
			this.compilerPanel.PerformLayout();
			base.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer components;
		public global::Guna.UI2.WinForms.Guna2Panel guna2Panel3;
		public global::Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
		public global::Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox2;
		public global::System.Windows.Forms.Label label1;
		public global::System.Windows.Forms.Label label3;
		private global::System.Windows.Forms.OpenFileDialog openFileDialog1;
		private global::Guna.UI2.WinForms.Guna2Panel builderPanel;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button4;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button3;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button2;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button1;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button5;
		private global::System.Windows.Forms.ListBox fileList;
		private global::Guna.UI2.WinForms.Guna2Panel compilerPanel;
		public global::System.Windows.Forms.Label label2;
		private global::Guna.UI2.WinForms.Guna2TextBox filenameTxt;
		private global::System.Windows.Forms.TextBox resultsTxt;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button6;
		private global::System.Windows.Forms.OpenFileDialog openFileDialog2;
		private global::Guna.UI2.WinForms.Guna2Button guna2Button7;
	}
}
